
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/databunch.ipynb

#================================================
from fastai.vision import *


#================================================
import cv2


#================================================
import os


#================================================
import torch


#================================================
def get_y(x, ds_rootdir, imgdir, maskdir):
    yfn = os.path.join(ds_rootdir, maskdir, '%s_mask%s' % (x.stem, x.suffix))
    #print(yfn, x.stem, x.suffix)
    return yfn


#================================================
def get_databunch(ds_root_dir = 'dataset_20200708', ds_imgdir = 'image'
                  , ds_maskdir = 'mask', bs = 16, valid_pct = 0.2
                  , transforms = get_transforms(max_zoom = 1.)):
    '''
    获取databunch
    参数：
        ds_root_dir：数据集的根目录
        ds_imgdir：图片子目录
        ds_maskdir: mask图片子目录
        bs：batch_size
        valid_pct:验证集百分比
        transforms: 无缩放，其余默认参数。
    返回值：
        databunch
    '''
    data = SegmentationItemList.from_folder( \
                    os.path.join(ds_root_dir, ds_imgdir))

    data = data.split_by_rand_pct(valid_pct)
    data = data.label_from_func( \
            partial(get_y, ds_rootdir = ds_root_dir, imgdir = ds_imgdir, maskdir = ds_maskdir) \
            , classes=['bg', 'water'])

    #import pdb; pdb.set_trace()
    data = data.transform(transforms, tfm_y = True)
    data = data.databunch(bs=bs, num_workers = 0, device=device)
    data = data.normalize(imagenet_stats)
    return data

